#!/bin/bash

battery_info=$(pmset -g batt)

charging_status=$(echo "$battery_info" | grep -o "'.*'" | tr -d "'")
battery_percentage=$(echo "$battery_info" | grep -o '[0-9]\{1,3\}%')

case "$charging_status" in
  "Battery Power")
    echo -n "↯ "
    ;;
  "AC Power")
    echo -n "⚡"
    ;;
  *)
    # echo -n "ϟ "
    echo -n "? "
    ;;
esac

echo "$battery_percentage"
