#!/bin/bash

# gfucc = git fixup commit chooser

# Present a list to choose a commit
selected_hash=$(git log --pretty=format:"%C(auto)%h%Creset -%C(auto)%d%Creset %s (%C(green)%cr%Creset)" --color=always | fzf --ansi --preview 'git show --color=always {1}' --exit-0 | cut -d ' ' -f 1)

# See if something was selected and commit to that hash
if [ -n "$selected_hash" ]; then
    git commit --fixup=$selected_hash "$@"
else
    echo "No commit selected."
fi
