#!/bin/bash

# gsbp = git switch branch picker

current=$(git branch --show-current)
selected_branch=$(
  git for-each-ref \
    --sort=-committerdate refs/heads/ \
    --format=$'%(if)%(HEAD)%(then)*%(else) %(end)\t%(refname:short)\t%(committername), %(committerdate:short)' \
    --color=always \
  | column -ts $'\t' \
  | fzf --ansi --delimiter=$'\s\s+' --with-nth=1,2,3 \
        --preview 'git diff --color=always '"$current"'..{2}' --exit-0 \
  | awk '{print $1}'
)

if [ -n "$selected_branch" ]; then
  git switch $selected_branch
else
  echo "No branch selected."
fi
