#!/bin/bash
tw_kube_context="$(kubectl config current-context 2> /dev/null)"
tw_kube_namespace="$(kubectl config view --minify -o jsonpath='{..namespace}' 2> /dev/null)"

if [[ $tw_kube_context != "" ]]; then
  echo -n "☸ "
  echo -n "$(basename $tw_kube_context)"
  if [[ $tw_kube_namespace != "" ]]; then
    echo -n ":$tw_kube_namespace"
  fi
fi
