#!/bin/bash

vpnstatus=$(osascript $DOTFILES/scripts/tunnelblick.applescript)

if [[ $vpnstatus =~ "CONNECTED" ]]; then
  echo "VPN✓ "
elif [[ $vpnstatus =~ "SLEEP" ]]; then
  echo "VPN~ "
elif [[ $vpnstatus =~ "AUTH" ]]; then
  echo "VPN…✓ "
elif [[ $vpnstatus =~ "GET_CONFIG" ]]; then
  echo "VPN…✓  "
elif [[ $vpnstatus =~ "DISCONNECTING" ]]; then
  echo "VPN† "
elif [[ $vpnstatus =~ "EXITING" ]]; then
  echo "VPN⨯ "
elif [[ $vpnstatus =~ "NOT_RUNNING" ]]; then
  echo ""
else
  echo "VPN? ($vpnstatus)"
fi 
